spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://guest-service
          predicates:
            - Path=/guest-service/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
              - Path=/payment-service/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


server:
  port: 8989