spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://guest-service
          predicates:
            - Path=/guest/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
              - Path=/payment/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


server:
  port: 8989